//! Who may talk to this gateway: the web login for a browser, or one minted
//! token for the client an embedded gateway was started by.
//!
//! A process has exactly one of them ([`GatewayAuth`], chosen at startup), which
//! is what keeps each mode free of the other's machinery.
//!
//! **The login.** TOML strings carry a bcrypt hash verbatim — its `$./` alphabet
//! needs no escaping: `[server].site_passwd` is plain `username:bcrypt_hash`
//! (generated by `alumia gen-passwd <username>`), `/api/auth/login` verifies a
//! username/password pair against it and mints a session token, and everything
//! guarded (the rest of `/api/*`, `/ws`) requires that token in the cookie.
//! A login lives in memory and slides: six hours from its last request, gone
//! with the browser and with the gateway. One the person asked to be kept
//! ("keep me signed in") lasts thirty days from the login instead, never
//! pushed out, and outlives both: its cookie carries the lifetime, and the
//! gateway writes the SHA-256 of its token, never the token, to a file in its
//! state directory ([`AuthSessions::open`]).
//!
//! **The token.** `alumia serve-embedded` has no user to ask and nowhere to keep
//! a credential: it is started for one managed browser instance. So it mints an
//! [`EmbeddedToken`], hands it to its parent down a pipe (see [`crate::embedded`]),
//! and takes it in the same `alumia_session` cookie a login would have set. The
//! parent control plane seeds it as an HttpOnly cookie on the instance subdomain,
//! which lets one page load carry it to `/api/*` and to the WebSocket upgrades alike
//! — a header cannot reach either from inside a document. Such a gateway still refuses `/api/auth/login`
//! and `/api/auth/logout`: there is no credential to check and no session to end.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use anyhow::Context as _;
#[cfg(feature = "embedded-gateway")]
use base64::Engine as _;
use log::warn;
#[cfg(feature = "embedded-gateway")]
use rand::RngExt as _;
use sha2::{Digest as _, Sha256};

use crate::cause::{Cause, Caused as _};
use crate::ensure_known;

/// Name of the auth session cookie.
pub const COOKIE_NAME: &str = "alumia_session";

/// Default bcrypt cost for `gen-passwd` (the crate default).
pub const DEFAULT_COST: u32 = bcrypt::DEFAULT_COST;

/// Sliding lifetime of a login that is not kept: every validated request pushes
/// the expiry out.
const SESSION_TTL: Duration = Duration::from_secs(6 * 60 * 60);

/// Lifetime of a kept login, counted from the login and never pushed out. An
/// absolute timeout, because it is what bounds a cookie that outlives the
/// browser: sliding, a kept login in use would never end.
pub const KEPT_TTL: Duration = Duration::from_secs(30 * 24 * 60 * 60);

/// The file a gateway's kept logins are written to, in its state directory.
pub const LOGINS_FILE: &str = "logins";

/// That file's first line: what it is, and the version of its layout.
const LOGINS_HEADER: &str = "alumia logins 1";

/// SHA-256 of `text`, as lowercase hexadecimal.
fn fingerprint(text: &str) -> String {
    use std::fmt::Write as _;

    let mut hex = String::with_capacity(64);
    for byte in Sha256::digest(text.as_bytes()).iter() {
        write!(hex, "{byte:02x}").expect("writing to a String cannot fail");
    }
    hex
}

/// The parsed `[server].site_passwd` credential: the one username allowed to
/// log in and the bcrypt hash of its password.
#[derive(Clone)]
pub struct SitePasswd {
    username: String,
    hash: String,
}

// Manual Debug so an AppConfig dump never prints the hash.
impl std::fmt::Debug for SitePasswd {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SitePasswd")
            .field("username", &self.username)
            .finish_non_exhaustive()
    }
}

impl SitePasswd {
    /// Parse the credential: `username:bcrypt_hash`, verbatim.
    pub fn parse(credential: &str) -> anyhow::Result<Self> {
        let (username, hash) = credential
            .trim()
            .split_once(':')
            .context("site_passwd must be username:bcrypt_hash")
            .cause(|| Cause::new("AL-9412"))?;
        ensure_known!("AL-9413"; !username.is_empty(), "site_passwd username is empty");
        ensure_known!(
            "AL-9414", username = username;
            ["$2a$", "$2b$", "$2y$"].iter().any(|p| hash.starts_with(p)),
            "site_passwd hash for user {username:?} is not bcrypt (want $2a$/$2b$/$2y$)"
        );
        Ok(Self {
            username: username.to_owned(),
            hash: hash.to_owned(),
        })
    }

    /// The username allowed to log in (for startup logging).
    pub fn username(&self) -> &str {
        &self.username
    }

    /// Check a login attempt. A wrong username still burns a bcrypt verify so
    /// the two rejections don't differ by timing.
    pub fn verify(&self, username: &str, password: &str) -> bool {
        let password_ok = bcrypt::verify(password, &self.hash).unwrap_or(false);
        password_ok && username == self.username
    }

    /// What the kept logins of this credential are written under, so that the
    /// file of another one — the password changed — lets nobody in.
    fn fingerprint(&self) -> String {
        fingerprint(&format!("alumia logins\0{}:{}", self.username, self.hash))
    }
}

/// How this process decides that a request may proceed at all.
///
/// One of the two, fixed at startup: a `serve` gateway can only be a
/// [`Self::Login`] and a `serve-embedded` one can only be a [`Self::Token`]. That
/// is the point of an enum here rather than two optional fields — neither mode
/// carries a way in that it does not use, and `require_auth` in
/// [`crate::server`] matches on this and on nothing else.
#[derive(Clone, Debug)]
pub enum GatewayAuth {
    /// A web login: the `[server].site_passwd` credential, the `alumia_session`
    /// cookie, and the [`AuthSessions`] behind it.
    Login(SitePasswd),
    /// One token, minted at startup and given to the client that started this
    /// gateway, which presents it as the same `alumia_session` cookie a login
    /// would have set. `/api/auth/login` and `/api/auth/logout` refuse on such a
    /// gateway: there is nothing to log in to and nothing to end.
    #[cfg(feature = "embedded-gateway")]
    Token(EmbeddedToken),
}

impl GatewayAuth {
    /// The login credential when this is a deployed gateway. A managed gateway
    /// has no interactive login endpoint.
    pub fn login(&self) -> Option<&SitePasswd> {
        match self {
            Self::Login(site_passwd) => Some(site_passwd),
            #[cfg(feature = "embedded-gateway")]
            Self::Token(_) => None,
        }
    }

    /// Validate the cookie using the only authentication scheme compiled into
    /// and selected for this process.
    pub fn authenticates(&self, sessions: &AuthSessions, presented: &str) -> bool {
        match self {
            Self::Login(_) => sessions.validate(presented),
            #[cfg(feature = "embedded-gateway")]
            Self::Token(expected) => expected.matches(presented),
        }
    }
}

/// The secret an embedded gateway and its one client share: 32 random bytes,
/// base64url, minted per launch.
///
/// Deliberately not hashed the way [`SitePasswd`] is. A hash protects a credential
/// at rest against whoever reads where it rests, and this one never rests: it is
/// generated in memory, written once to a pipe held by the process that spawned
/// this one, and gone when this one exits. There is also nobody to be slow for —
/// bcrypt's cost exists to make guessing a *human's* password expensive, and 32
/// random bytes are not guessable at any cost.
#[cfg(feature = "embedded-gateway")]
#[derive(Clone)]
pub struct EmbeddedToken(String);

// Manual Debug so a config dump — which carries the whole `GatewayAuth` — cannot
// print the one secret that would let anything drive the remote.
#[cfg(feature = "embedded-gateway")]
impl std::fmt::Debug for EmbeddedToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("EmbeddedToken(…)")
    }
}

#[cfg(feature = "embedded-gateway")]
impl EmbeddedToken {
    /// How many random bytes the token carries.
    const BYTES: usize = 32;

    /// Mint a fresh token from the OS random source.
    pub fn generate() -> Self {
        let mut bytes = [0u8; Self::BYTES];
        rand::rng().fill(&mut bytes);
        Self(base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes))
    }

    /// The value to hand the client, and the only place it is readable.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Whether a presented value is this token, without leaking *where* it stops
    /// matching.
    ///
    /// The length is not a secret — every token this mints is the same length — so
    /// a mismatched length answers immediately. The bytes are, so they are folded
    /// into one accumulator rather than compared with an early return.
    pub fn matches(&self, presented: &str) -> bool {
        secrets_match(&self.0, presented)
    }
}

/// Whether two secrets are the same, without leaking *where* they stop matching.
///
/// A free function because the same token is checked in two places: here, by the
/// embedded gateway holding the [`EmbeddedToken`], and by the control plane's
/// router, which reads it out of a cookie before proxying
/// ([`crate::embedded::manager`]) and never holds the token type at all. One
/// comparison, so there is no second copy to be the one that compares with `==`.
#[cfg(feature = "embedded-gateway")]
pub fn secrets_match(expected: &str, presented: &str) -> bool {
    let expected = expected.as_bytes();
    let presented = presented.as_bytes();
    if expected.len() != presented.len() {
        return false;
    }
    let mut difference = 0u8;
    for (a, b) in expected.iter().zip(presented) {
        difference |= a ^ b;
    }
    difference == 0
}

/// Generate a `site_passwd` value (the `gen-passwd` subcommand; tests pass a
/// low cost to keep logins fast).
pub fn generate(username: &str, password: &str, cost: u32) -> anyhow::Result<String> {
    ensure_known!("AL-9415"; !username.is_empty(), "username must not be empty");
    ensure_known!("AL-9416"; !username.contains(':'), "username must not contain ':'");
    ensure_known!("AL-9417"; !password.is_empty(), "password must not be empty");
    let hash = bcrypt::hash(password, cost).context("bcrypt hash failed")?;
    Ok(format!("{username}:{hash}"))
}

/// Both clocks a login is held against, read once per call.
#[derive(Clone, Copy)]
struct Now {
    /// For a login that slides: monotonic, so a clock that is set moves nothing.
    instant: Instant,
    /// For a kept login, whose expiry has to mean the same after a restart: Unix
    /// seconds.
    unix: u64,
}

impl Now {
    fn read() -> Self {
        let unix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |since| since.as_secs());
        Self { instant: Instant::now(), unix }
    }
}

/// When a login stops being one.
#[derive(Clone, Copy)]
enum Expiry {
    /// Pushed out by every validated request.
    Sliding(Instant),
    /// Fixed at the login, in Unix seconds, and never pushed out.
    Kept(u64),
}

impl Expiry {
    fn live(self, now: Now) -> bool {
        match self {
            Self::Sliding(until) => until > now.instant,
            Self::Kept(until) => until > now.unix,
        }
    }
}

/// Where a gateway's kept logins are written, and whose they are.
struct KeptFile {
    path: PathBuf,
    /// [`SitePasswd::fingerprint`] of the credential they were made under.
    credential: String,
}

impl KeptFile {
    /// The kept logins still live at `now`, and whether the file holds anything
    /// else: an expired login, one that would last longer than a kept login
    /// does, a line that is not one, another credential's.
    fn read(&self, now: Now) -> anyhow::Result<(HashMap<String, Expiry>, bool)> {
        let text = match std::fs::read_to_string(&self.path) {
            Ok(text) => text,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                return Ok((HashMap::new(), false));
            }
            Err(e) => {
                return Err(e).with_context(|| format!("cannot read {}", self.path.display()));
            }
        };
        let mut lines = text.lines();
        anyhow::ensure!(
            lines.next() == Some(LOGINS_HEADER),
            "{} is not a file of kept logins",
            self.path.display()
        );
        if lines.next() != Some(self.credential.as_str()) {
            // The password changed, and what the old one let in goes with it.
            return Ok((HashMap::new(), true));
        }
        let mut logins = HashMap::new();
        let mut stale = false;
        for line in lines {
            let entry = line
                .split_once(' ')
                .and_then(|(digest, until)| Some((digest, until.parse::<u64>().ok()?)));
            // Live, and no further off than a login made now would be: a line
            // that says more than that was not written by this gateway.
            let latest = now.unix + KEPT_TTL.as_secs();
            match entry {
                Some((digest, until)) if until > now.unix && until <= latest => {
                    logins.insert(digest.to_owned(), Expiry::Kept(until));
                }
                _ => stale = true,
            }
        }
        Ok((logins, stale))
    }

    /// Write the kept logins among `logins`: the header, the credential's
    /// fingerprint, then a token's SHA-256 and its expiry on each line. Staged
    /// beside the file and renamed over it, so a gateway killed mid-write leaves
    /// the file it had.
    fn write(&self, logins: &HashMap<String, Expiry>) -> anyhow::Result<()> {
        use std::io::Write as _;

        let mut kept: Vec<String> = logins
            .iter()
            .filter_map(|(digest, expiry)| match expiry {
                Expiry::Kept(until) => Some(format!("{digest} {until}\n")),
                Expiry::Sliding(_) => None,
            })
            .collect();
        kept.sort();
        let text = format!("{LOGINS_HEADER}\n{}\n{}", self.credential, kept.concat());

        if let Some(dir) = self.path.parent() {
            std::fs::create_dir_all(dir)
                .with_context(|| format!("cannot create {}", dir.display()))?;
        }
        let staged = self.path.with_extension("tmp");
        let mut options = std::fs::OpenOptions::new();
        options.write(true).create(true).truncate(true);
        // The owner's alone. What it holds logs nobody in, and it still says when
        // somebody signed in and until when.
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt as _;
            options.mode(0o600);
        }
        let mut file = options
            .open(&staged)
            .with_context(|| format!("cannot write {}", staged.display()))?;
        // The mode above is only given to a file this call creates.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt as _;
            file.set_permissions(std::fs::Permissions::from_mode(0o600))
                .with_context(|| format!("cannot set the mode of {}", staged.display()))?;
        }
        file.write_all(text.as_bytes())
            .with_context(|| format!("cannot write {}", staged.display()))?;
        drop(file);
        std::fs::rename(&staged, &self.path)
            .with_context(|| format!("cannot replace {}", self.path.display()))
    }
}

/// The gateway's logins: the SHA-256 of each token → its expiry. The map only
/// ever holds this single user's handful of logins, so expired entries are
/// swept opportunistically on create/validate instead of by a timer.
///
/// Keyed by the digest and not the token, so that what is written to disk for a
/// kept login is nothing that logs anybody in.
pub struct AuthSessions {
    logins: Mutex<HashMap<String, Expiry>>,
    ttl: Duration,
    /// Where kept logins are written. `None` keeps them in memory, for the life
    /// of the process: an embedded gateway, which has no login, and tests.
    kept: Option<KeptFile>,
}

impl Default for AuthSessions {
    fn default() -> Self {
        Self::with_ttl(SESSION_TTL)
    }
}

impl AuthSessions {
    fn with_ttl(ttl: Duration) -> Self {
        Self {
            logins: Mutex::new(HashMap::new()),
            ttl,
            kept: None,
        }
    }

    /// Logins whose kept ones are written to `path` and read back from it, so
    /// they outlive the gateway. A file that cannot be read, or that is not
    /// one of these, starts the gateway with none and says so: a login is what
    /// that costs, and a gateway that did not start would cost the desktop.
    pub fn open(path: &Path, site_passwd: &SitePasswd) -> Self {
        Self::open_at(path, site_passwd, Now::read())
    }

    fn open_at(path: &Path, site_passwd: &SitePasswd, now: Now) -> Self {
        let kept = KeptFile {
            path: path.to_owned(),
            credential: site_passwd.fingerprint(),
        };
        let (logins, stale) = kept.read(now).unwrap_or_else(|e| {
            warn!("starting with no kept logins: {e:#}");
            (HashMap::new(), false)
        });
        let sessions = Self {
            logins: Mutex::new(logins),
            ttl: SESSION_TTL,
            kept: Some(kept),
        };
        if stale {
            sessions.persist(&sessions.logins.lock().unwrap());
        }
        sessions
    }

    /// Write the kept logins out, under the lock the caller holds: a few lines,
    /// written whole. A failure costs them their life across a restart and
    /// nothing else, so it is said and not returned.
    ///
    /// It is file work, so the two callers a request makes on purpose, a login
    /// and a logout, run off the async workers (`server::login_handler`,
    /// `server::logout_handler`). The third is `validate` finding a kept login
    /// that has ended, once in that login's life.
    fn persist(&self, logins: &HashMap<String, Expiry>) {
        let Some(kept) = &self.kept else {
            return;
        };
        if let Err(e) = kept.write(logins) {
            warn!("kept logins will not outlive this gateway: {e:#}");
        }
    }

    /// Mint a session token after a successful login, kept or sliding.
    pub fn create(&self, keep: bool) -> String {
        self.create_at(keep, Now::read())
    }

    fn create_at(&self, keep: bool, now: Now) -> String {
        let token = uuid::Uuid::new_v4().to_string();
        let mut logins = self.logins.lock().unwrap();
        // The sweep. A kept login it takes leaves the file with it, whoever is
        // signing in: an ended login is not left written down.
        let mut ended_kept = false;
        logins.retain(|_, expiry| {
            let live = expiry.live(now);
            ended_kept |= !live && matches!(expiry, Expiry::Kept(_));
            live
        });
        let expiry = if keep {
            Expiry::Kept(now.unix + KEPT_TTL.as_secs())
        } else {
            Expiry::Sliding(now.instant + self.ttl)
        };
        logins.insert(fingerprint(&token), expiry);
        if keep || ended_kept {
            self.persist(&logins);
        }
        token
    }

    /// True when the token names a live login. A sliding one is pushed out; a
    /// kept one is not.
    pub fn validate(&self, token: &str) -> bool {
        self.validate_at(token, Now::read())
    }

    fn validate_at(&self, token: &str, now: Now) -> bool {
        let digest = fingerprint(token);
        let mut logins = self.logins.lock().unwrap();
        match logins.get_mut(&digest) {
            Some(expiry) if expiry.live(now) => {
                if let Expiry::Sliding(until) = expiry {
                    *until = now.instant + self.ttl;
                }
                true
            }
            Some(expiry) => {
                let kept = matches!(expiry, Expiry::Kept(_));
                logins.remove(&digest);
                if kept {
                    self.persist(&logins);
                }
                false
            }
            None => false,
        }
    }

    /// Drop a login (logout), from the file too where it was kept.
    pub fn invalidate(&self, token: &str) {
        let mut logins = self.logins.lock().unwrap();
        if let Some(Expiry::Kept(_)) = logins.remove(&fingerprint(token)) {
            self.persist(&logins);
        }
    }
}

/// Extract this app's session token from a request's `Cookie` header.
pub fn token_from_headers(headers: &axum::http::HeaderMap) -> Option<String> {
    let cookies = headers.get(axum::http::header::COOKIE)?.to_str().ok()?;
    cookies.split(';').find_map(|pair| {
        let (name, value) = pair.trim().split_once('=')?;
        (name == COOKIE_NAME).then(|| value.to_owned())
    })
}

#[cfg(test)]
mod tests {
    use axum::http::{HeaderMap, HeaderValue, header};

    use super::*;

    // bcrypt's minimum cost, so tests don't burn CPU on real key stretching.
    const TEST_COST: u32 = 4;

    #[test]
    fn generate_parse_verify_roundtrip() {
        let encoded = generate("admin", "hunter2", TEST_COST).unwrap();
        let site = SitePasswd::parse(&encoded).unwrap();
        assert_eq!(site.username(), "admin");
        assert!(site.verify("admin", "hunter2"));
        assert!(!site.verify("admin", "wrong"));
        assert!(!site.verify("mallory", "hunter2"), "username must match too");
    }

    #[test]
    fn generate_rejects_bad_input() {
        assert!(generate("", "pw", TEST_COST).is_err());
        assert!(generate("a:b", "pw", TEST_COST).is_err(), "':' would corrupt the format");
        assert!(generate("admin", "", TEST_COST).is_err());
    }

    #[test]
    fn parse_rejects_malformed_credentials() {
        let msg = |s: &str| format!("{:#}", SitePasswd::parse(s).unwrap_err());
        assert!(msg("just-a-username").contains("username:bcrypt_hash"));
        assert!(msg(":$2b$04$hash").contains("username is empty"));
        assert!(msg("admin:$1$legacy$hash").contains("bcrypt"), "only bcrypt hashes");
    }

    #[test]
    fn sessions_validate_refresh_and_invalidate() {
        let sessions = AuthSessions::default();
        let token = sessions.create(false);
        assert!(sessions.validate(&token));
        assert!(!sessions.validate("no-such-token"));
        sessions.invalidate(&token);
        assert!(!sessions.validate(&token));
    }

    #[test]
    fn expired_sessions_are_rejected() {
        let sessions = AuthSessions::with_ttl(Duration::ZERO);
        let token = sessions.create(false);
        assert!(!sessions.validate(&token), "a zero-TTL session is born expired");
    }

    /// A login nobody asked to keep lasts six hours from its last request: used
    /// inside them it goes on, and left alone for them it ends.
    #[test]
    fn a_login_that_is_not_kept_slides_six_hours_from_its_last_request() {
        assert_eq!(SESSION_TTL, Duration::from_secs(6 * 60 * 60));
        let sessions = AuthSessions::default();
        let start = Instant::now();
        let after = |hours: u64| Now {
            instant: start + Duration::from_secs(hours * 60 * 60),
            unix: 0,
        };
        let token = sessions.create_at(false, after(0));
        assert!(sessions.validate_at(&token, after(5)));
        assert!(sessions.validate_at(&token, after(10)), "pushed out by the request at five");
        assert!(!sessions.validate_at(&token, after(16)), "six hours with no request");
        assert!(!sessions.validate_at(&token, after(17)), "and it does not come back");
    }

    fn site(password: &str) -> SitePasswd {
        SitePasswd::parse(&generate("admin", password, TEST_COST).unwrap()).unwrap()
    }

    /// A moment `secs` after the Unix epoch, on a monotonic clock that reads now.
    fn at(secs: u64) -> Now {
        Now { instant: Instant::now(), unix: secs }
    }

    fn written(path: &Path) -> String {
        std::fs::read_to_string(path).unwrap()
    }

    /// A login nobody asked to keep is the login it always was: in memory, and
    /// nowhere a restart could find it.
    #[test]
    fn a_login_that_is_not_kept_is_never_written() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let sessions = AuthSessions::open(&path, &site("hunter2"));
        let token = sessions.create(false);
        assert!(sessions.validate(&token));
        assert!(!path.exists(), "nothing was kept, so nothing is written");

        // Beside a kept one, which is written, it is still not.
        let kept = sessions.create(true);
        assert!(written(&path).contains(&fingerprint(&kept)));
        assert!(!written(&path).contains(&fingerprint(&token)));
    }

    /// What reaches the disk is the token's SHA-256 and its expiry: a file that
    /// is read by somebody else logs nobody in.
    #[test]
    fn a_kept_login_is_written_as_its_digest_and_never_as_its_token() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let site = site("hunter2");
        let sessions = AuthSessions::open_at(&path, &site, at(1_000));
        let token = sessions.create_at(true, at(1_000));

        let text = written(&path);
        assert!(!text.contains(&token), "the token itself is in the file: {text}");
        assert_eq!(
            text,
            format!(
                "{LOGINS_HEADER}\n{}\n{} {}\n",
                site.fingerprint(),
                fingerprint(&token),
                1_000 + KEPT_TTL.as_secs()
            )
        );
        assert_eq!(KEPT_TTL.as_secs(), 2_592_000, "thirty days");
    }

    #[cfg(unix)]
    #[test]
    fn the_file_of_kept_logins_is_its_owners_alone() {
        use std::os::unix::fs::PermissionsExt as _;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        AuthSessions::open(&path, &site("hunter2")).create(true);
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600);
    }

    /// The point of writing it: a gateway that restarts still knows the login.
    #[test]
    fn a_kept_login_outlives_the_gateway() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let site = site("hunter2");
        let token = AuthSessions::open_at(&path, &site, at(1_000)).create_at(true, at(1_000));

        let restarted = AuthSessions::open_at(&path, &site, at(2_000));
        assert!(restarted.validate_at(&token, at(2_000)));
        assert!(!restarted.validate_at("no-such-token", at(2_000)));
    }

    /// Thirty days from the login, however much it is used: a kept login that
    /// slid would never end.
    #[test]
    fn a_kept_login_ends_thirty_days_after_the_login_and_is_never_pushed_out() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let site = site("hunter2");
        let sessions = AuthSessions::open_at(&path, &site, at(1_000));
        let token = sessions.create_at(true, at(1_000));
        let end = 1_000 + KEPT_TTL.as_secs();

        // Used on its last second, which a sliding login would be pushed out by.
        assert!(sessions.validate_at(&token, at(end - 1)));
        assert!(!sessions.validate_at(&token, at(end)), "used, and still ended on time");
        assert!(!written(&path).contains(&fingerprint(&token)), "and it left the file");

        // One that ended while the gateway was down is not read back, and leaves
        // the file at the start.
        let other = AuthSessions::open_at(&path, &site, at(5_000)).create_at(true, at(5_000));
        let late = 5_000 + KEPT_TTL.as_secs();
        let restarted = AuthSessions::open_at(&path, &site, at(late));
        assert!(!restarted.validate_at(&other, at(late)));
        assert!(!written(&path).contains(&fingerprint(&other)));
    }

    /// Whoever signs in next sweeps the ended logins, and a kept one that ended
    /// leaves the file then, whether or not the new login is kept.
    #[test]
    fn a_kept_login_that_ended_leaves_the_file_at_the_next_login() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let sessions = AuthSessions::open_at(&path, &site("hunter2"), at(1_000));
        let ended = sessions.create_at(true, at(1_000));
        assert!(written(&path).contains(&fingerprint(&ended)));

        sessions.create_at(false, at(1_000 + KEPT_TTL.as_secs()));
        assert!(!written(&path).contains(&fingerprint(&ended)), "{}", written(&path));
    }

    /// A line that promises more than thirty days from now was not written by
    /// this gateway, and lets nobody in.
    #[test]
    fn a_login_the_file_gives_more_than_thirty_days_is_not_read() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let site = site("hunter2");
        let token = AuthSessions::open_at(&path, &site, at(1_000)).create_at(true, at(1_000));
        let honest = 1_000 + KEPT_TTL.as_secs();
        std::fs::write(&path, written(&path).replace(&honest.to_string(), &(honest + 1).to_string()))
            .unwrap();

        let restarted = AuthSessions::open_at(&path, &site, at(1_000));
        assert!(!restarted.validate_at(&token, at(1_000)));
        assert!(!written(&path).contains(&fingerprint(&token)));
    }

    /// A file that cannot be written costs the login its life across a restart
    /// and nothing else: it is still a login.
    #[test]
    fn a_kept_login_that_cannot_be_written_still_logs_in() {
        let dir = tempfile::tempdir().unwrap();
        // The state directory is a file: nothing can be created under it.
        let not_a_directory = dir.path().join("state");
        std::fs::write(&not_a_directory, "").unwrap();
        let path = not_a_directory.join(LOGINS_FILE);

        let sessions = AuthSessions::open(&path, &site("hunter2"));
        let token = sessions.create(true);
        assert!(sessions.validate(&token));
        assert!(!path.exists());
    }

    #[test]
    fn logging_out_takes_a_kept_login_out_of_the_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let site = site("hunter2");
        let sessions = AuthSessions::open(&path, &site);
        let (stays, goes) = (sessions.create(true), sessions.create(true));
        sessions.invalidate(&goes);

        assert!(!sessions.validate(&goes));
        assert!(!written(&path).contains(&fingerprint(&goes)));
        let restarted = AuthSessions::open(&path, &site);
        assert!(!restarted.validate(&goes), "a restart does not bring it back");
        assert!(restarted.validate(&stays), "and the other login is untouched");
    }

    /// A changed password ends what the old one let in, kept or not.
    #[test]
    fn another_password_reads_none_of_the_kept_logins() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        let token = AuthSessions::open(&path, &site("hunter2")).create(true);

        let changed = AuthSessions::open(&path, &site("another"));
        assert!(!changed.validate(&token));
        assert!(!written(&path).contains(&fingerprint(&token)), "and it is gone from the file");
    }

    /// A file that is not one of these starts the gateway with no kept login
    /// rather than stopping it, and is left alone until there is one to write.
    #[test]
    fn a_file_that_is_not_kept_logins_keeps_nobody_in() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOGINS_FILE);
        std::fs::write(&path, "something else\n").unwrap();
        let site = site("hunter2");
        let sessions = AuthSessions::open(&path, &site);
        assert_eq!(written(&path), "something else\n");

        // A line that is not a login is dropped, and the logins beside it kept.
        let token = sessions.create(true);
        let text = format!("{}not a login\n", written(&path));
        std::fs::write(&path, text).unwrap();
        let restarted = AuthSessions::open(&path, &site);
        assert!(restarted.validate(&token));
        assert!(!written(&path).contains("not a login"));
    }

    /// A minted token matches itself and nothing else, including the near misses a
    /// hand-rolled constant-time compare could get wrong: a prefix, an extension,
    /// and the empty string.
    #[cfg(feature = "embedded-gateway")]
    #[test]
    fn an_embedded_token_matches_only_itself() {
        let token = EmbeddedToken::generate();
        assert!(token.matches(token.as_str()));
        assert!(!token.matches(""));
        assert!(!token.matches(&token.as_str()[..token.as_str().len() - 1]), "a prefix");
        assert!(!token.matches(&format!("{}x", token.as_str())), "an extension");
        assert!(!token.matches(EmbeddedToken::generate().as_str()), "another token");
    }

    /// Two launches never share a secret, and the encoding is URL-safe base64 so
    /// the value can sit in a header untouched.
    #[cfg(feature = "embedded-gateway")]
    #[test]
    fn embedded_tokens_are_fresh_and_header_safe() {
        let (a, b) = (EmbeddedToken::generate(), EmbeddedToken::generate());
        assert_ne!(a.as_str(), b.as_str());
        // 32 bytes, base64 without padding.
        assert_eq!(a.as_str().len(), 43, "{}", a.as_str());
        assert!(
            a.as_str()
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'),
            "{}",
            a.as_str()
        );
    }

    /// The one secret that would drive the remote must not be printable by
    /// accident: `AppConfig` derives Debug and carries this.
    #[cfg(feature = "embedded-gateway")]
    #[test]
    fn an_embedded_token_is_not_in_its_debug_output() {
        let token = EmbeddedToken::generate();
        let auth = GatewayAuth::Token(token.clone());
        for rendered in [format!("{token:?}"), format!("{auth:?}")] {
            assert!(!rendered.contains(token.as_str()), "{rendered}");
        }
        assert!(auth.login().is_none(), "a token gateway has no login");
    }

    #[test]
    fn token_is_found_among_other_cookies() {
        let mut headers = HeaderMap::new();
        headers.insert(
            header::COOKIE,
            HeaderValue::from_str(&format!("other=1; {COOKIE_NAME}=tok-123; x=y")).unwrap(),
        );
        assert_eq!(token_from_headers(&headers).as_deref(), Some("tok-123"));

        let mut headers = HeaderMap::new();
        headers.insert(header::COOKIE, HeaderValue::from_static("other=1"));
        assert_eq!(token_from_headers(&headers), None);
        assert_eq!(token_from_headers(&HeaderMap::new()), None);
    }
}
